# Generated by Django 4.2.11 on 2024-03-30 12:54

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0034_alter_item_vitamin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('F', 'fruit'), ('V', 'vegetable'), ('J', 'junk food'), ('D', 'dairy product'), ('S', 'sweets')], max_length=1),
        ),
        migrations.AlterField(
            model_name='target',
            name='tr_vitamins',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('A', 'A'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('K', 'K'), ('B1', 'B1'), ('B2', 'B2'), ('B3', 'B3'), ('B6', 'B6'), ('B12', 'B12'), ('B5', 'B5'), ('B7', 'B7'), ('B9', 'B9')], default=1, max_length=100, null=True),
        ),
    ]
