# Generated by Django 4.2.11 on 2024-03-30 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0035_alter_item_category_alter_target_tr_vitamins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='target',
            name='tr_ingredient',
        ),
    ]
