# Generated by Django 4.2.11 on 2024-03-31 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0036_remove_target_tr_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('F', 'fruit'), ('V', 'vegetable'), ('J', 'junk food'), ('D', 'dairy product'), ('S', 'sweets'), ('K', 'drink'), ('R', 'farsan')], max_length=1),
        ),
    ]
