# Generated by Django 4.2.11 on 2024-03-31 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0037_alter_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('F', 'fruit'), ('V', 'vegetable'), ('J', 'junk food'), ('D', 'dairy product'), ('S', 'sweets'), ('C', 'cold drink')], max_length=1),
        ),
    ]
